on: 
 pull_request:
    types:
      - closed

jobs:
  linked_issues:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Find Linked Issues
        id: links
        uses: hossainemruz/linked-issues@main
        with:
          pr_url: ${{github.event.pull_request.html_url}}
          format: IssueNumber

      - name: Output linked Issue list
        run: echo "${{ steps.links.outputs.issues }}"
      - uses: actions/checkout@v3
      - env:
          GITHUB_TOKEN: ${{ secrets.MGITHUB_TOKEN }}
          #ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit "${{ steps.links.outputs.issues }}" --add-label "QA"
          gh issue edit "${{ steps.links.outputs.issues }}" --remove-assignee "@me"
          gh issue edit "${{ steps.links.outputs.issues }}" --add-assignee ali-saeed91
